image: docker:19.03.12

stages:
  - build

services:
  - docker:19.03.12-dind

builder:
  stage: build
  tags:
    - docker
  script:
    - docker login $TOKEN_URL -u $TOKEN_USER -p $TOKEN_PASS
    - cd web
    - docker build -t $TOKEN_URL/matrix-widgets/stickerpicker .
    - docker save $TOKEN_URL/matrix-widgets/stickerpicker -o stickerpicker.tar
    - docker push $TOKEN_URL/matrix-widgets/stickerpicker
  artifacts:
    paths:
      - web/stickerpicker.tar
