image: docker:19.03.12

stages:
  - build

services:
  - docker:19.03.12-dind

builder-to-registry:
  stage: build
  tags:
    - docker
  script:
    - docker login $TOKEN_URL -u $TOKEN_USER -p $TOKEN_PASS
    - cd web
    - docker build -t $TOKEN_URL/stickerpicker .
    - docker push $TOKEN_URL/stickerpicker


builder:
  stage: build
  tags:
    - docker
  script:
    - cd web
    - docker build -t $TOKEN_URL/stickerpicker .
    - docker save $TOKEN_URL/stickerpicker -o stickerpicker.tar
  artifacts:
    paths:
    - web/stickerpicker.tar
